#!/usr/bin/env bash
# Convenience wrapper for using `ls` and `less` interactively

l() {
    if [[ $# -eq 0 ]]
    then
        # argcount: 0
        ls -lh --color
    elif [[ $# -eq 1 ]]
    then
        # argcount: 1
        if [[ -f "${1}" ]]
        then
            # regular file
            local cat="cat"
            if command -v pyg &>/dev/null
            then
                cat="pyg"
            fi
            "${cat}" "${1}" | less -RF
        else
            # not a regular file
            ls -lh --color "${1}"
        fi

    else
        # argcount: >1
        ls -lh --color "$@"
    fi
}
