#!/bin/bash
shopt -s extglob
shopt -s dotglob
DESTINATION=${DESTINATION-$HOME}
for file in !(*README*|.git|.gitmodules|install|*.swp); do
    echo Linking ${file}
    ln -sf `readlink -f ${file}` ${DESTINATION}
done
