#!/bin/bash
shopt -s extglob
shopt -s dotglob

DESTINATION=${DESTINATION-$HOME}

for DOTFILE in home/!(*.swp)
do
    if [[ -L "${DOTFILE}" ]]
    then
        echo Copying symlink "${DOTFILE}" to "${DESTINATION}"
        cp -P "${DOTFILE}" "${DESTINATION}"
    else
        TARGET=$(readlink -f "${DOTFILE}")
        echo Linking "${DOTFILE}" from "${TARGET}" to "${DESTINATION}"
        ln -sf "${TARGET}" ${DESTINATION}
    fi
done
